export const LOGIN_POST_API_REQUEST = 'LOGIN_POST_API_REQUEST';
export const LOGIN_POST_API_SUCCESS = 'LOGIN_POST_API_SUCCESS';
export const LOGIN_POST_API_FAILURE = 'LOGIN_POST_API_FAILURE';

export const SET_NET_INFO = 'SET_NET_INFO';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';

export const PRESENT_LOADER = 'PRESENT_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const PRESENT_MODAL = 'PRESENT_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const CLEAR_MODAL = 'CLEAR_MODAL';

export const RESET_STORE = 'RESET_STORE';

export const MOVIE_LIST_API_REQUEST = 'MOVIE_LIST_API_REQUEST';
export const MOVIE_LIST_API_SUCCESS = 'MOVIE_LIST_API_SUCCESS';
export const MOVIE_LIST_API_FAILURE = 'MOVIE_LIST_API_FAILURE';

export const ADD_SELECTED_SEAT = 'ADD_SELECTED_SEAT';
export const CLEAR_SELECTEd_SEAT = 'CLEAR_SELECTEd_SEAT';
